"use client";

import { CalendarClock, ChevronDown, ChevronRight, Clapperboard, Download, ExternalLink, Film, MessagesSquare, Play, RefreshCw, Search, Settings, Trash2, WandSparkles, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { jobTtsEngineLabel } from "../lib/languages";
import { platformEligibility, platforms, publishedPlatformLabel } from "../lib/platforms";
import { fetchPublishingReadiness, serviceFetch, SERVICE_URL } from "../lib/service";
import type { LocalJob, PublishingReadiness, ToolJob } from "../lib/types";
import { PlatformLogo } from "./common";

type LibraryItem = {
  id: string;
  kind: "job" | "short";
  title: string;
  description?: string;
  mode: string;
  sourceLabel: string;
  source: string;
  sourceUrl?: string;
  sourceGroupId?: string;
  sourceTitle?: string;
  createdAt: string;
  state: LocalJob["state"];
  thumbnailUrl?: string;
  videoUrl?: string;
  downloadUrl?: string;
  detail: string;
  job?: LocalJob;
  toolJob?: ToolJob;
};

const libraryModeOptions = [
  { id: "all", label: "All modes", description: "Every video in this workspace", icon: Film },
  { id: "Prompt to Video", label: "Prompt to Video", description: "Narrated videos created from reviewed prompts", icon: WandSparkles },
  { id: "Message Conversation", label: "Message Conversation", description: "Fictional phone conversations recorded from approved timelines", icon: MessagesSquare },
  { id: "Long Video to Shorts", label: "Long Video to Shorts", description: "Shorts produced from uploaded videos and public URLs", icon: Clapperboard },
  { id: "Quick Create", label: "Quick Create", description: "Fast videos created from the Quick Create composer", icon: Zap },
  { id: "Automation", label: "Automation", description: "Videos generated by scheduled pipelines", icon: CalendarClock },
] as const;

export function LibraryView({ authenticated, onRequireAuthentication, onCreateVideo, onOpenJob, onOpenSettings, setToast }: {
  authenticated: boolean;
  onRequireAuthentication: () => boolean;
  onCreateVideo: () => void;
  onOpenJob: (job: LocalJob) => void;
  onOpenSettings: () => void;
  setToast: (value: string) => void;
}) {
  const [query, setQuery] = useState("");
  const [selectedMode, setSelectedMode] = useState("all");
  const [expandedSourceIds, setExpandedSourceIds] = useState<Record<string, boolean>>({});
  const [localJobs, setLocalJobs] = useState<LocalJob[]>([]);
  const [toolJobs, setToolJobs] = useState<ToolJob[]>([]);
  const [readiness, setReadiness] = useState<PublishingReadiness | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const refreshJobs = async () => {
    if (!authenticated) return void onRequireAuthentication();
    try {
      const [jobsResponse, toolsResponse] = await Promise.all([
        serviceFetch(`${SERVICE_URL}/jobs`).then((response) => response.json()) as Promise<{ jobs?: LocalJob[] }>,
        serviceFetch(`${SERVICE_URL}/tool-jobs`).then((response) => response.json()) as Promise<{ jobs?: ToolJob[] }>,
      ]);
      setLocalJobs(jobsResponse.jobs ?? []);
      setToolJobs(toolsResponse.jobs ?? []);
    } catch {
      setLocalJobs([]);
      setToolJobs([]);
    }
  };

  useEffect(() => {
    if (!authenticated) {
      const clear = window.setTimeout(() => {
        setLocalJobs([]);
        setToolJobs([]);
        setReadiness(null);
      }, 0);
      return () => window.clearTimeout(clear);
    }
    let cancelled = false;
    Promise.all([
      serviceFetch(`${SERVICE_URL}/jobs`).then((response) => response.json()) as Promise<{ jobs?: LocalJob[] }>,
      serviceFetch(`${SERVICE_URL}/tool-jobs`).then((response) => response.json()) as Promise<{ jobs?: ToolJob[] }>,
    ]).then(([jobsResponse, toolsResponse]) => {
      if (cancelled) return;
      setLocalJobs(jobsResponse.jobs ?? []);
      setToolJobs(toolsResponse.jobs ?? []);
    }).catch(() => {
      if (cancelled) return;
      setLocalJobs([]);
      setToolJobs([]);
    });
    void fetchPublishingReadiness().then((value) => { if (!cancelled) setReadiness(value); }).catch(() => { if (!cancelled) setReadiness(null); });
    return () => { cancelled = true; };
  }, [authenticated]);

  const libraryItems = useMemo(() => buildLibraryItems(localJobs, toolJobs), [localJobs, toolJobs]);
  const normalizedQuery = query.trim().toLowerCase();
  const searchedItems = libraryItems.filter((item) => !normalizedQuery || [item.title, item.description ?? "", item.mode, item.source, item.sourceTitle ?? "", item.detail].some((value) => value.toLowerCase().includes(normalizedQuery)));
  const modeOptions = libraryModeOptions.map((mode) => ({
    ...mode,
    count: mode.id === "all" ? libraryItems.length : libraryItems.filter((item) => item.mode === mode.id).length,
  }));
  const visibleModeOptions = selectedMode === "all"
    ? modeOptions.filter((mode) => mode.id !== "all" && searchedItems.some((item) => item.mode === mode.id))
    : modeOptions.filter((mode) => mode.id === selectedMode);
  const visibleItemCount = selectedMode === "all" ? searchedItems.length : searchedItems.filter((item) => item.mode === selectedMode).length;

  async function deleteVideo(job: LocalJob) {
    if (!authenticated) return void onRequireAuthentication();
    const confirmed = window.confirm(`Permanently delete “${job.metadata?.title ?? job.request.prompt.slice(0, 70)}” and every local video, audio, subtitle, transcript, thumbnail, clip, and metadata file?`);
    if (!confirmed) return;
    setDeletingId(job.id);
    try {
      const response = await serviceFetch(`${SERVICE_URL}/jobs/${job.id}`, { method: "DELETE" });
      const result = await response.json() as { error?: string };
      if (!response.ok) throw new Error(result.error ?? "Video could not be deleted");
      setLocalJobs((jobs) => jobs.filter((item) => item.id !== job.id));
      setToast("Video and all local assets deleted");
    } catch (error) {
      setToast(error instanceof Error ? error.message : "Video could not be deleted");
    } finally {
      setDeletingId(null);
    }
  }

  function renderVideoItem(item: LibraryItem) {
    const eligible = item.job ? platforms.filter((platform) => platformEligibility(item.job!, platform.id, readiness).eligible) : [];
    const published = item.job ? platforms.map((platform) => ({ platform, label: publishedPlatformLabel(item.job!.publishResults?.[platform.id]) })).filter((entry) => entry.label) : [];
    return <article className="library-video-item" key={item.id}>
      <a className="library-video-thumb" href={item.videoUrl ? `${SERVICE_URL}${item.videoUrl}` : undefined} target={item.videoUrl ? "_blank" : undefined} rel="noreferrer" onClick={(event) => {
        if (item.job) {
          event.preventDefault();
          onOpenJob(item.job);
        }
      }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        {item.thumbnailUrl ? <img src={`${SERVICE_URL}${item.thumbnailUrl}`} alt={`${item.title} thumbnail`} /> : <span><Film size={20} /></span>}
        <em>{item.kind === "short" ? "SHORT" : "VIDEO"}</em>
        {item.videoUrl && <i><Play size={12} /></i>}
      </a>
      <div className="library-video-copy">
        <div className="library-mode-line"><strong>{item.mode}</strong><span>{item.sourceLabel}</span></div>
        <h2>{item.title}</h2>
        {item.description && <p>{item.description}</p>}
        <small className="library-video-source">From: {item.sourceUrl
          ? <a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.source}<ExternalLink size={10} /></a>
          : item.source}</small>
        <small>{item.detail}</small>
        {item.job && <span className="library-platform-summary">
          <span><b>Eligible</b>{eligible.length ? eligible.map((platform) => <em key={platform.id} title={`${platform.label}: ready to upload`}><PlatformLogo platform={platform} /><span className="sr-only">{platform.label}</span></em>) : <i>None</i>}</span>
          <span><b>Published</b>{published.length ? published.map(({ platform, label }) => <em className="published" key={platform.id} title={`${platform.label}: ${label}`}><PlatformLogo platform={platform} /><span>{label}</span></em>) : <i>None</i>}</span>
        </span>}
      </div>
      <span className={`status-label ${item.state === "completed" ? "published" : item.state === "failed" || item.state === "stopped" ? "rendering" : "ready"}`}><i />{item.state}</span>
      <div className="real-job-actions">
        {item.job && <button onClick={() => onOpenJob(item.job!)}>View details</button>}
        {item.videoUrl && !item.job && <a className="library-preview-action" href={`${SERVICE_URL}${item.videoUrl}`} target="_blank" rel="noreferrer"><Play size={13} /> Preview</a>}
        {item.downloadUrl && <a href={`${SERVICE_URL}${item.downloadUrl}`} aria-label={`Download ${item.title}`}><Download size={14} /></a>}
        {item.job && <button className="delete-video-button" onClick={() => void deleteVideo(item.job!)} disabled={deletingId === item.job.id || item.state === "running" || item.state === "queued"} title={item.state === "running" || item.state === "queued" ? "Wait for rendering to finish" : "Delete video and every local asset"}><Trash2 size={13} /> {deletingId === item.job.id ? "Deleting…" : "Delete"}</button>}
      </div>
    </article>;
  }

  return (
    <div className="content-wrap library-page">
      <div className="page-heading">
        <div><div className="eyebrow"><span /> CONTENT LIBRARY</div><h1>Every generated video, in one place.</h1><p>See the creation mode, original source, reusable output, and publishing status for each video.</p></div>
      </div>
      <div className="library-toolbar">
        <label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search videos, modes, and sources" /></label>
        <div><span className="library-total-count">{libraryItems.length} total</span><button onClick={onOpenSettings}><Settings size={13} /> Manage platforms</button><button onClick={() => void refreshJobs()}><RefreshCw size={13} /> Refresh</button></div>
      </div>
      <nav className="library-mode-switcher" aria-label="Video library modes">
        {modeOptions.map((mode) => {
          const Icon = mode.icon;
          return <button className={selectedMode === mode.id ? "active" : ""} onClick={() => setSelectedMode(mode.id)} key={mode.id}><i><Icon size={16} /></i><span><strong>{mode.label}</strong><small>{mode.count} video{mode.count === 1 ? "" : "s"}</small></span></button>;
        })}
      </nav>
      {visibleItemCount > 0 && <div className="library-mode-lists">
        {visibleModeOptions.map((mode) => {
          const ModeIcon = mode.icon;
          const items = searchedItems.filter((item) => item.mode === mode.id);
          const sourceGroups = mode.id === "Long Video to Shorts" ? groupLongVideoItems(items) : [];
          return <section className="real-jobs library-video-list" key={mode.id}>
            <div className="real-jobs-title"><span><ModeIcon size={14} /> {mode.label}</span><small>{mode.description} · {sourceGroups.length ? `${sourceGroups.length} source${sourceGroups.length === 1 ? "" : "s"} · ` : ""}{items.length} video{items.length === 1 ? "" : "s"}</small></div>
            {mode.id === "Long Video to Shorts" ? sourceGroups.map((group, groupIndex) => {
              const expanded = normalizedQuery ? true : expandedSourceIds[group.id] ?? groupIndex === 0;
              return <article className={`library-source-group ${expanded ? "expanded" : ""}`} key={group.id}>
                <div className="library-video-item library-source-summary">
                  <span className="library-video-thumb">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  {group.thumbnailUrl ? <img src={`${SERVICE_URL}${group.thumbnailUrl}`} alt={`${group.title} source group`} /> : <span><Clapperboard size={20} /></span>}
                  <em>SOURCE</em>
                  <i>{group.items.length}</i>
                  </span>
                  <div className="library-video-copy">
                    <div className="library-mode-line"><strong>Long Video to Shorts</strong><span>{group.sourceLabel}</span></div>
                    <h2>{group.title}</h2>
                    <p>{group.sourceUrl
                      ? <a href={group.sourceUrl} target="_blank" rel="noreferrer">{group.source}<ExternalLink size={10} /></a>
                      : group.source}</p>
                    <small>{group.items.length} generated short{group.items.length === 1 ? "" : "s"} • expand to review each publishing package</small>
                  </div>
                  <span className={`status-label ${group.state === "completed" ? "published" : group.state === "failed" || group.state === "stopped" ? "rendering" : "ready"}`}><i />{group.state}</span>
                  <div className="real-job-actions">
                    <button className="library-expand-button" aria-expanded={expanded} aria-controls={`source-videos-${group.id}`} onClick={() => setExpandedSourceIds((current) => ({ ...current, [group.id]: !expanded }))}>
                      {expanded ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
                      {expanded ? "Hide videos" : `Show ${group.items.length} video${group.items.length === 1 ? "" : "s"}`}
                    </button>
                  </div>
                </div>
                {expanded && <div className="library-source-children" id={`source-videos-${group.id}`}>{group.items.map((item) => renderVideoItem(item))}</div>}
              </article>;
            }) : items.map((item) => renderVideoItem(item))}
          </section>;
        })}
      </div>}
      {visibleItemCount === 0 && <div className="empty-library"><Film size={28} /><strong>{query ? "No matching videos" : selectedMode === "all" ? "Your video library is empty" : `No ${selectedMode} videos yet`}</strong><p>{query ? "Try a different search or mode." : "Generate a new video package and it will appear in this mode."}</p><button className="primary-small" onClick={onCreateVideo}><Clapperboard size={16} /> Browse creation modes</button></div>}
    </div>
  );
}

function buildLibraryItems(localJobs: LocalJob[], toolJobs: ToolJob[]): LibraryItem[] {
  const toolsById = new Map(toolJobs.map((job) => [job.id, job]));
  const items: LibraryItem[] = localJobs.map((job) => {
    const longVideoPackage = job.metadata?.creationMode === "long-video-shorts";
    const messageConversation = job.metadata?.creationMode === "message-conversation";
    const sourceDescriptor = longVideoPackage
      ? describeLongVideoSource(toolsById.get(job.metadata?.sourceToolJobId ?? ""), toolsById, job.metadata)
      : null;
    const mode = messageConversation
      ? "Message Conversation"
      : longVideoPackage
      ? "Long Video to Shorts"
      : job.trigger?.type === "automation" || job.trigger?.type === "cron"
      ? "Automation"
      : job.request.approvedScript && job.request.visualThemes?.length && job.request.visualSelections?.length
        ? "Prompt to Video"
        : "Quick Create";
    const sourceUrl = sourceDescriptor?.sourceUrl ?? "";
    return {
      id: `job-${job.id}`,
      kind: longVideoPackage ? "short" : "job",
      title: job.metadata?.title ?? job.request.prompt.slice(0, 90),
      description: job.metadata?.description,
      mode,
      sourceLabel: messageConversation ? "Fictional script" : longVideoPackage ? sourceDescriptor?.sourceLabel ?? "From upload" : "From prompt",
      source: messageConversation ? job.request.conversation?.events.map((event) => event.text).filter(Boolean).slice(0, 3).join(" · ") || job.request.prompt : longVideoPackage ? sourceDescriptor?.source ?? "Uploaded long video" : job.request.prompt,
      sourceUrl: sourceUrl || undefined,
      sourceGroupId: sourceDescriptor?.groupId,
      sourceTitle: sourceDescriptor?.title,
      createdAt: job.createdAt,
      state: job.state,
      thumbnailUrl: job.assets?.thumbnail?.url,
      videoUrl: job.assets?.final?.url,
      downloadUrl: job.assets?.final?.downloadUrl,
      detail: messageConversation
        ? `${job.metadata?.conversationParticipants?.length ?? 0} participants • ${job.metadata?.conversationLayout ?? "phone"} • ${job.metadata?.conversationAudioMode ?? "silent"} audio • fictional`
        : `${job.metadata?.narrator ?? "Default narrator"} • ${job.request.language} ${jobTtsEngineLabel(job)} • ${job.request.subtitleLanguage} captions${longVideoPackage ? " • publish-ready package" : ""}`,
      job,
    };
  });
  const promotedShorts = new Set(localJobs
    .filter((job) => job.metadata?.creationMode === "long-video-shorts" && job.metadata.sourceToolJobId && job.metadata.sourceAssetKey)
    .map((job) => `${job.metadata!.sourceToolJobId}:${job.metadata!.sourceAssetKey}`));
  for (const toolJob of toolJobs.filter((job) => job.request.toolId === "long-video-render")) {
    const clips = Array.isArray(toolJob.metadata?.clips) ? toolJob.metadata.clips as Array<Record<string, unknown>> : [];
    const sourceDescriptor = describeLongVideoSource(toolJob, toolsById);
    const videoAssets = Object.entries(toolJob.assets ?? {}).filter(([key, asset]) => /^short\d+$/.test(key) && asset.type === "video");
    for (const [index, [assetKey, asset]] of videoAssets.entries()) {
      if (promotedShorts.has(`${toolJob.id}:${assetKey}`)) continue;
      const clip = clips.find((value) => value.assetKey === assetKey) ?? clips[index] ?? {};
      const thumbnailKey = String(clip.thumbnailAssetKey || `${assetKey}Thumbnail`);
      const thumbnail = toolJob.assets?.[thumbnailKey];
      items.push({
        id: `short-${toolJob.id}-${assetKey}`,
        kind: "short",
        title: String(clip.title || asset.name),
        description: typeof clip.description === "string" ? clip.description : typeof clip.reason === "string" ? clip.reason : undefined,
        mode: "Long Video to Shorts",
        sourceLabel: sourceDescriptor.sourceLabel,
        source: sourceDescriptor.source,
        sourceUrl: sourceDescriptor.sourceUrl || undefined,
        sourceGroupId: sourceDescriptor.groupId,
        sourceTitle: sourceDescriptor.title,
        createdAt: toolJob.createdAt,
        state: toolJob.state,
        thumbnailUrl: thumbnail?.url,
        videoUrl: asset.url,
        downloadUrl: asset.downloadUrl,
        detail: `${formatSeconds(Number(clip.duration))} • ${String(clip.framing || "center")} framing • ${toolJob.metadata?.captions === false ? "captions off" : "captions on"}`,
        toolJob,
      });
    }
  }
  return items.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

type LongVideoSourceGroup = {
  id: string;
  title: string;
  sourceLabel: string;
  source: string;
  sourceUrl?: string;
  thumbnailUrl?: string;
  state: LibraryItem["state"];
  createdAt: string;
  items: LibraryItem[];
};

function groupLongVideoItems(items: LibraryItem[]): LongVideoSourceGroup[] {
  const groups = new Map<string, LongVideoSourceGroup>();
  for (const item of items) {
    const id = item.sourceGroupId || `source:${item.sourceUrl || item.source}`;
    const existing = groups.get(id);
    if (existing) {
      existing.items.push(item);
      if (item.createdAt > existing.createdAt) existing.createdAt = item.createdAt;
      existing.state = combinedState(existing.items);
      if (!existing.thumbnailUrl && item.thumbnailUrl) existing.thumbnailUrl = item.thumbnailUrl;
      continue;
    }
    groups.set(id, {
      id,
      title: item.sourceTitle || sourceTitle(item.sourceUrl),
      sourceLabel: item.sourceLabel,
      source: item.source,
      sourceUrl: item.sourceUrl,
      thumbnailUrl: item.thumbnailUrl,
      state: item.state,
      createdAt: item.createdAt,
      items: [item],
    });
  }
  return Array.from(groups.values())
    .map((group) => ({ ...group, items: group.items.sort((a, b) => b.createdAt.localeCompare(a.createdAt)), state: combinedState(group.items) }))
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

function describeLongVideoSource(renderJob: ToolJob | undefined, toolsById: Map<string, ToolJob>, metadata?: LocalJob["metadata"]) {
  const mediaReference = renderJob?.request.inputs.media;
  const mediaToolJob = mediaReference?.toolJobId ? toolsById.get(mediaReference.toolJobId) : undefined;
  const metadataUrl = typeof metadata?.sourceUrl === "string" ? metadata.sourceUrl : "";
  const toolUrl = typeof mediaToolJob?.request.options.url === "string" ? mediaToolJob.request.options.url : "";
  const sourceUrl = metadataUrl || toolUrl;
  const uploadId = mediaReference?.uploadId;
  const mediaKey = mediaReference?.toolJobId
    ? `${mediaReference.toolJobId}:${mediaReference.assetKey || "video"}`
    : uploadId || renderJob?.id || metadata?.sourceToolJobId || "unknown";
  const title = typeof metadata?.sourceTitle === "string" && metadata.sourceTitle.trim()
    ? metadata.sourceTitle.trim()
    : sourceTitle(sourceUrl);
  return {
    groupId: sourceUrl ? `url:${sourceUrl}` : uploadId ? `upload:${uploadId}` : `media:${mediaKey}`,
    title,
    sourceLabel: sourceUrl ? "From URL" : "From upload",
    source: sourceUrl || title,
    sourceUrl,
  };
}

function sourceTitle(sourceUrl?: string) {
  if (!sourceUrl) return "Uploaded long video";
  try {
    const hostname = new URL(sourceUrl).hostname.replace(/^www\./, "");
    if (hostname === "youtube.com" || hostname === "youtu.be") return "YouTube source video";
    return `${hostname} source video`;
  } catch {
    return "Public source video";
  }
}

function combinedState(items: LibraryItem[]): LibraryItem["state"] {
  if (items.some((item) => item.state === "running")) return "running";
  if (items.some((item) => item.state === "queued")) return "queued";
  if (items.some((item) => item.state === "failed")) return "failed";
  if (items.some((item) => item.state === "stopped")) return "stopped";
  return "completed";
}

function formatSeconds(value: number) {
  return Number.isFinite(value) && value > 0 ? `${Math.round(value)} sec` : "Short video";
}
