"use client";

import {
  Check,
  ChevronDown,
  CircleHelp,
  Clock3,
  ExternalLink,
  Play,
  RefreshCw,
  ShieldCheck,
  X,
} from "lucide-react";
import { useState } from "react";
import { platforms } from "../lib/platforms";
import type { FacebookStatus, InstagramStatus, TikTokStatus, YouTubeStatus } from "../lib/types";
import { PlatformLogo } from "./common";

function SetupOverview({ time, prerequisites, result }: { time: string; prerequisites: string[]; result: string }) {
  return <div className="setup-overview"><div><strong>Before you start</strong><ul>{prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></div><div><strong>What to expect</strong><p><Clock3 size={13} /> About {time}</p><p><ShieldCheck size={13} /> {result}</p></div></div>;
}

function SetupDone({ children }: { children: React.ReactNode }) {
  return <p className="setup-done"><Check size={13} /> <span><b>You are done with this step when:</b> {children}</span></p>;
}

function CopyCode({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  async function copy() {
    await navigator.clipboard.writeText(value);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  }
  return <div className="copy-code"><code>{value}</code><button onClick={() => void copy()}>{copied ? <><Check size={13} /> Copied</> : "Copy"}</button></div>;
}

function SetupTroubleshooting({ issues }: { issues: Array<{ title: string; fix: string }> }) {
  return <details className="setup-troubleshooting"><summary><CircleHelp size={16} /><span><strong>Something not working?</strong><small>Open common errors and exact fixes</small></span><ChevronDown size={15} /></summary><div>{issues.map((issue) => <p key={issue.title}><b>{issue.title}</b><span>{issue.fix}</span></p>)}</div></details>;
}

export function YouTubeSetupGuide({ status, clientId, clientSecret, setClientId, setClientSecret, showSecret, setShowSecret, connecting, onConnect, onCheck, onClose }: { status: YouTubeStatus | null; clientId: string; clientSecret: string; setClientId: (value: string) => void; setClientSecret: (value: string) => void; showSecret: boolean; setShowSecret: (value: boolean) => void; connecting: boolean; onConnect: () => void; onCheck: () => void; onClose: () => void }) {
  const redirectUri = status?.redirectUri ?? "http://127.0.0.1:8788/oauth/youtube/callback";
  return <div className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="youtube-setup-title"><div className="setup-dialog">
    <header><div><PlatformLogo platform={platforms[0]} /><span><strong id="youtube-setup-title">Connect YouTube</strong><small>One-time Google Cloud and OAuth setup</small></span></div><button onClick={onClose} aria-label="Close YouTube setup"><X size={18} /></button></header>
    {status?.connected && <div className="connection-success"><ShieldCheck size={18} /><span><strong>{status.channelTitle} is connected</strong><small>Reelio verified upload access for this channel.</small></span></div>}
    <SetupOverview time="10–15 minutes" prerequisites={["A Google account that owns or manages a YouTube channel", "Access to Google Cloud Console", "Reelio running on this Mac while you connect"]} result="Reelio receives a refresh token and can upload to the selected channel." />
    <ol className="setup-steps">
      <li><span>1</span><div><strong>Confirm the correct YouTube channel</strong><ul className="setup-actions"><li>Open YouTube and sign in with the Google account you want Reelio to use.</li><li>Click your profile picture and confirm the channel name. Create a channel first if YouTube asks you to.</li></ul><a href="https://www.youtube.com/account" target="_blank" rel="noreferrer">Open YouTube account <ExternalLink size={13} /></a><SetupDone>The channel name you expect is visible in YouTube.</SetupDone></div></li>
      <li><span>2</span><div><strong>Create or select a Google Cloud project</strong><ul className="setup-actions"><li>Open the project page and click <b>Create project</b>.</li><li>Name it <b>Reelio</b>, create it, then use the project selector at the top to make sure Reelio is selected.</li></ul><a href="https://console.cloud.google.com/projectcreate" target="_blank" rel="noreferrer">Open Google Cloud projects <ExternalLink size={13} /></a><SetupDone>The top bar in Google Cloud shows your Reelio project.</SetupDone></div></li>
      <li><span>3</span><div><strong>Enable YouTube Data API v3</strong><ul className="setup-actions"><li>Open the API page while the Reelio project is selected.</li><li>Press <b>Enable</b>. If the button says <b>Manage</b>, it is already enabled.</li></ul><a href="https://console.cloud.google.com/apis/library/youtube.googleapis.com" target="_blank" rel="noreferrer">Open YouTube Data API v3 <ExternalLink size={13} /></a><SetupDone>The page shows “API enabled.”</SetupDone></div></li>
      <li><span>4</span><div><strong>Set up Google Auth Platform</strong><ul className="setup-actions"><li>Open Google Auth Platform → <b>Branding</b>. Enter app name <b>Reelio</b>, your support email, and developer email.</li><li>Open <b>Audience</b>. Choose <b>External</b> for a personal Google account. Leave the app in Testing while only you use it.</li><li>Open <b>Data Access</b> and add <code>youtube.upload</code> and <code>youtube.readonly</code> if Google asks you to declare scopes.</li></ul><a href="https://console.cloud.google.com/auth/overview" target="_blank" rel="noreferrer">Open Google Auth Platform <ExternalLink size={13} /></a><SetupDone>Branding, Audience, and contact information are saved.</SetupDone></div></li>
      <li><span>5</span><div><strong>Add yourself as a test user</strong><ul className="setup-actions"><li>Go to Google Auth Platform → <b>Audience</b> → <b>Test users</b>.</li><li>Click <b>Add users</b> and enter the exact Google email that owns the YouTube channel.</li><li>Save. This prevents the “developer-approved testers only” 403 error.</li></ul><SetupDone>Your Google email appears in the Test users list.</SetupDone></div></li>
      <li><span>6</span><div><strong>Create the OAuth client</strong><ul className="setup-actions"><li>Open <b>Clients</b> → <b>Create client</b>.</li><li>Application type: <b>Web application</b>. Name: <b>Reelio local app</b>.</li><li>Under <b>Authorized redirect URIs</b>, click <b>Add URI</b> and paste the value below exactly. Do not add a trailing slash.</li></ul><CopyCode value={redirectUri} /><a href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noreferrer">Open OAuth clients <ExternalLink size={13} /></a><SetupDone>Google shows a Client ID ending in <code>apps.googleusercontent.com</code> and a Client secret.</SetupDone></div></li>
      <li><span>7</span><div><strong>Paste the credentials and connect</strong><ul className="setup-actions"><li>Copy the Client ID and Client secret from Google into the fields below.</li><li>Press <b>Save &amp; connect YouTube</b>.</li><li>In Google&apos;s window, choose the correct account, press <b>Continue</b>, allow access, and wait for “YouTube connected.”</li></ul><div className="youtube-credential-grid"><label><span>Client ID</span><input value={clientId} onChange={(event) => setClientId(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "…apps.googleusercontent.com"} autoComplete="off" /></label><label><span>Client secret</span><div><input type={showSecret ? "text" : "password"} value={clientSecret} onChange={(event) => setClientSecret(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "Google OAuth client secret"} autoComplete="off" /><button onClick={() => setShowSecret(!showSecret)}>{showSecret ? "Hide" : "Show"}</button></div></label></div><SetupDone>This guide shows the connected channel name in green.</SetupDone></div></li>
    </ol>
    <div className="youtube-setup-note"><CircleHelp size={16} /><p><b>Testing versus production:</b> test users can connect immediately. Google restricts videos uploaded by unverified API projects created after July 28, 2020 to private viewing. Public API uploads require Google&apos;s YouTube API audit; changing Reelio&apos;s privacy setting cannot bypass it.</p></div>
    <SetupTroubleshooting issues={[{ title: "Error 403: access_denied", fix: "Add the exact Google account under Google Auth Platform → Audience → Test users, then connect again." }, { title: "redirect_uri_mismatch", fix: `Edit the Web OAuth client and add exactly ${redirectUri}. Check http, 127.0.0.1, port 8788, path, and trailing slash.` }, { title: "Connected account has no channel", fix: "Open YouTube with that Google account and create/select its channel, then reconnect." }, { title: "Upload is private", fix: "This is a Google audit restriction for unverified YouTube API projects, not a Reelio upload setting." }]} />
    <footer><button className="secondary-action" onClick={onCheck}><RefreshCw size={15} /> Check connection</button><button className="youtube-connect-button" onClick={onConnect} disabled={connecting || status?.connected}>{status?.connected ? <><Check size={16} /> Connected</> : connecting ? <><RefreshCw className="spin" size={16} /> Starting…</> : <><Play size={16} /> {status?.configured && !clientId && !clientSecret ? "Connect YouTube" : "Save & connect YouTube"}</>}</button></footer>
  </div></div>;
}

export function TikTokSetupGuide({ status, clientKey, clientSecret, setClientKey, setClientSecret, showSecret, setShowSecret, connecting, onConnect, onCheck, onClose }: { status: TikTokStatus | null; clientKey: string; clientSecret: string; setClientKey: (value: string) => void; setClientSecret: (value: string) => void; showSecret: boolean; setShowSecret: (value: boolean) => void; connecting: boolean; onConnect: () => void; onCheck: () => void; onClose: () => void }) {
  const redirectUri = status?.redirectUri ?? "http://127.0.0.1:8788/oauth/tiktok/callback";
  return <div className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="tiktok-setup-title"><div className="setup-dialog">
    <header><div><PlatformLogo platform={platforms[1]} /><span><strong id="tiktok-setup-title">Connect TikTok</strong><small>Login Kit Desktop • Content Posting Upload API</small></span></div><button onClick={onClose} aria-label="Close TikTok setup"><X size={18} /></button></header>
    {status?.connected && <div className="connection-success"><ShieldCheck size={18} /><span><strong>{status.displayName} is connected</strong><small>Reelio verified profile and draft-upload access.</small></span></div>}
    <SetupOverview time="15–25 minutes" prerequisites={["A TikTok account you can use as a Sandbox target user", "A TikTok for Developers account", "A public HTTPS website for app information, such as https://nainglin.com/nika/"]} result="Reelio uploads a draft; you finish and publish it from TikTok’s inbox." />
    <ol className="setup-steps">
      <li><span>1</span><div><strong>Create the TikTok developer app</strong><ul className="setup-actions"><li>Sign in to TikTok for Developers and open <b>Manage apps</b>.</li><li>Click <b>Connect an app</b> or <b>Create app</b>. Use app name <b>Reelio</b>.</li><li>For the official website field, enter a real public HTTPS page such as <code>https://nainglin.com/nika/</code>. Do not enter the localhost callback here.</li></ul><a href="https://developers.tiktok.com/apps/" target="_blank" rel="noreferrer">Open TikTok developer apps <ExternalLink size={13} /></a><SetupDone>You can open Reelio&apos;s app dashboard and see a Client key.</SetupDone></div></li>
      <li><span>2</span><div><strong>Use the Sandbox while the app is unapproved</strong><ul className="setup-actions"><li>Open the app, then find <b>Sandbox</b> in the app dashboard.</li><li>Add your TikTok account as a Sandbox target user and accept the invitation in TikTok.</li><li>Use that same account when Reelio opens the authorization window.</li></ul><SetupDone>The account appears as an active Sandbox target user.</SetupDone></div></li>
      <li><span>3</span><div><strong>Add the Desktop platform</strong><ul className="setup-actions"><li>In the app dashboard, open <b>Platform configuration</b> and add <b>Desktop</b>.</li><li>The public <b>Web/Desktop URL</b> must begin with HTTPS; use your official website.</li><li>Desktop OAuth is different: its redirect URI may use <code>http://127.0.0.1</code> because the callback returns to the app running on your Mac.</li></ul><SetupDone>Desktop is listed under the app&apos;s platforms.</SetupDone></div></li>
      <li><span>4</span><div><strong>Add and configure Login Kit</strong><ul className="setup-actions"><li>Click <b>Add products</b> → <b>Login Kit</b>.</li><li>Open Login Kit configuration and add the exact redirect URI below.</li><li>Do not change 127.0.0.1 to localhost, add parameters, or add a trailing slash.</li></ul><CopyCode value={redirectUri} /><a href="https://developers.tiktok.com/doc/login-kit-desktop/" target="_blank" rel="noreferrer">Open Desktop Login Kit instructions <ExternalLink size={13} /></a><SetupDone>The redirect URI is saved under Desktop Login Kit.</SetupDone></div></li>
      <li><span>5</span><div><strong>Add Content Posting API</strong><ul className="setup-actions"><li>Click <b>Add products</b> → <b>Content Posting API</b>.</li><li>Enable the <b>Upload API</b>, which sends drafts to the user&apos;s TikTok inbox.</li><li>Request or enable scopes <code>user.info.basic</code> and <code>video.upload</code>. Reelio does not currently require <code>video.publish</code>.</li></ul><a href="https://developers.tiktok.com/products/content-posting-api/" target="_blank" rel="noreferrer">Open Content Posting API <ExternalLink size={13} /></a><SetupDone>Content Posting API and <code>video.upload</code> appear in the app configuration.</SetupDone></div></li>
      <li><span>6</span><div><strong>Copy the Client key and Client secret</strong><ul className="setup-actions"><li>Open <b>Manage apps</b> → Reelio → <b>Basic information</b>.</li><li>Copy <b>Client key</b>.</li><li>Press <b>Show</b> beside <b>Client secret</b> and copy it. Never paste the secret into a public form or demo recording.</li></ul><div className="youtube-credential-grid"><label><span>Client key</span><input value={clientKey} onChange={(event) => setClientKey(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "TikTok client key"} autoComplete="off" /></label><label><span>Client secret</span><div><input type={showSecret ? "text" : "password"} value={clientSecret} onChange={(event) => setClientSecret(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "TikTok client secret"} autoComplete="off" /><button onClick={() => setShowSecret(!showSecret)}>{showSecret ? "Hide" : "Show"}</button></div></label></div><SetupDone>Both credential fields are filled.</SetupDone></div></li>
      <li><span>7</span><div><strong>Connect the Sandbox TikTok account</strong><ul className="setup-actions"><li>Press <b>Save &amp; connect TikTok</b> below.</li><li>In TikTok&apos;s window, sign in with the accepted Sandbox target account.</li><li>Approve basic profile and upload permission, then return to Reelio.</li></ul><SetupDone>The account name appears in green with “draft upload ready.”</SetupDone></div></li>
      <li><span>8</span><div><strong>Test the complete draft flow</strong><ul className="setup-actions"><li>In a finished Reelio video, select TikTok and press upload.</li><li>Wait until Reelio says <b>Delivered to TikTok inbox</b>.</li><li>Open TikTok on your phone → <b>Inbox</b> → system notification, finish editing, and publish.</li></ul><SetupDone>The draft opens in TikTok and can be posted by the creator.</SetupDone></div></li>
    </ol>
    <div className="youtube-setup-note tiktok-note"><CircleHelp size={16} /><p><b>Why Reelio sends a draft:</b> the approved Upload API uses <code>video.upload</code> and requires the creator to finish posting in TikTok. Fully automatic Direct Post uses <code>video.publish</code>, mandatory creator-info UI, explicit consent, and a separate TikTok audit. Unaudited Direct Post content is restricted to private.</p></div>
    <SetupTroubleshooting issues={[{ title: "Refresh token is invalid or expired", fix: "Open this guide and connect TikTok again with the Sandbox target account. Reelio will replace the expired refresh token." }, { title: "Redirect URI is rejected", fix: `Confirm Desktop—not Web—is configured and save exactly ${redirectUri}. The public Web/Desktop URL is a separate HTTPS website field.` }, { title: "scope_not_authorized or video.upload missing", fix: "Add Content Posting API, enable Upload API, enable video.upload, then reconnect so the new permission is included in the token." }, { title: "Upload succeeded but nothing is public", fix: "This is expected for Upload API. Open the TikTok inbox notification and complete the post manually." }, { title: "Too many pending shares", fix: "TikTok allows at most five pending uploads in 24 hours. Finish or clear pending drafts, then retry later." }]} />
    <footer><button className="secondary-action" onClick={onCheck}><RefreshCw size={15} /> Check connection</button><button className="youtube-connect-button tiktok-connect-button" onClick={onConnect} disabled={connecting || status?.connected}>{status?.connected ? <><Check size={16} /> Connected</> : connecting ? <><RefreshCw className="spin" size={16} /> Starting…</> : <><Play size={16} /> {status?.configured && !clientKey && !clientSecret ? "Connect TikTok" : "Save & connect TikTok"}</>}</button></footer>
  </div></div>;
}

export function FacebookSetupGuide({ status, appId, appSecret, setAppId, setAppSecret, showSecret, setShowSecret, connecting, selecting, onConnect, onSelectPage, onCheck, onClose }: { status: FacebookStatus | null; appId: string; appSecret: string; setAppId: (value: string) => void; setAppSecret: (value: string) => void; showSecret: boolean; setShowSecret: (value: boolean) => void; connecting: boolean; selecting: boolean; onConnect: () => void; onSelectPage: (pageId: string) => void; onCheck: () => void; onClose: () => void }) {
  const redirectUri = status?.redirectUri ?? "https://localhost:8789/oauth/facebook/callback";
  return <div className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="facebook-setup-title"><div className="setup-dialog">
    <header><div><PlatformLogo platform={platforms[2]} /><span><strong id="facebook-setup-title">Connect Facebook</strong><small>Meta Login • Facebook &amp; Instagram Reels Publishing</small></span></div><button onClick={onClose} aria-label="Close Facebook setup"><X size={18} /></button></header>
    {status?.connected && <div className="connection-success"><ShieldCheck size={18} /><span><strong>{status.pageName} is connected</strong><small>Reelio received a Page access token for this Page from Meta.</small></span></div>}
    {status?.needsPageSelection && status.pages?.length ? <div className="facebook-page-picker"><strong>Choose the Facebook Page to publish to</strong><div className="facebook-page-list">{status.pages.map((page) => <button key={page.id} onClick={() => onSelectPage(page.id)} disabled={selecting}><span>{page.name}</span><span className="page-id">{page.id}</span></button>)}</div><small>Reelio saves that Page&apos;s access token and, if the Page has a linked Instagram Professional account, its Instagram ID too.</small></div> : null}
    <SetupOverview time="5–10 minutes" prerequisites={["A Facebook Page—not a personal profile", "Facebook access with full control of that Page", "A Meta developer app you can add Facebook Login to"]} result="Reelio signs in with Meta and receives a non-expiring Page access token — no manual token copying." />
    <ol className="setup-steps">
      <li><span>1</span><div><strong>Create or open the Meta app</strong><ul className="setup-actions"><li>Open Meta for Developers → <b>My Apps</b> and create an app (or open your existing Reelio app).</li><li>For testing, keep the app in <b>Development</b> mode. Only app administrators, developers, and testers can authorize it.</li></ul><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer">Open Meta developer apps <ExternalLink size={13} /></a><SetupDone>The Reelio app dashboard opens and shows its App ID and App secret.</SetupDone></div></li>
      <li><span>2</span><div><strong>Add the Facebook Login product</strong><ul className="setup-actions"><li>In the app dashboard, click <b>Add product</b> and add <b>Facebook Login</b> (the “for Business” variant is fine).</li><li>Reelio requests the scopes <code>pages_show_list</code>, <code>pages_read_engagement</code>, <code>pages_manage_posts</code>, and <code>business_management</code> for Facebook, plus <code>instagram_basic</code> and <code>instagram_content_publish</code> so one login also connects Instagram.</li></ul><SetupDone>Facebook Login appears under Products in the app dashboard.</SetupDone></div></li>
      <li><span>3</span><div><strong>Enable the trusted HTTPS callback</strong><ul className="setup-actions"><li>Meta rejects <code>http://</code> redirect URIs, so Reelio serves this callback over HTTPS on localhost.</li><li>In your terminal, run <code>npm run https:setup</code> once. It installs a locally-trusted certificate with mkcert (you may be prompted for your macOS password), then restart <code>npm run dev</code>.</li></ul><CopyCode value="npm run https:setup" /><SetupDone>The terminal prints “HTTPS is ready” and the worker logs an <code>https://localhost</code> address on restart.</SetupDone></div></li>
      <li><span>4</span><div><strong>Register the redirect URI</strong><ul className="setup-actions"><li>Open <b>Facebook Login → Settings</b>.</li><li>Under <b>Valid OAuth Redirect URIs</b>, add the value below exactly, then save. Do not add a trailing slash.</li></ul><CopyCode value={redirectUri} /><SetupDone>The redirect URI is saved in Facebook Login settings.</SetupDone></div></li>
      <li><span>5</span><div><strong>Confirm your Page role</strong><ul className="setup-actions"><li>Open Meta Business Settings → <b>Accounts</b> → <b>Pages</b> and confirm your profile has <b>Full control</b> of the Page, or at least permission to create content.</li><li>To also publish Instagram Reels, make sure the Instagram Professional account is linked to that same Page.</li></ul><a href="https://business.facebook.com/settings/pages/" target="_blank" rel="noreferrer">Open Pages in Business Settings <ExternalLink size={13} /></a><SetupDone>Your profile manages the Page and (optionally) its linked Instagram account.</SetupDone></div></li>
      <li><span>6</span><div><strong>Paste the App ID and secret, then connect</strong><ul className="setup-actions"><li>Copy the <b>App ID</b> and <b>App secret</b> from Meta → <b>App settings → Basic</b> into the fields below.</li><li>Press <b>Save &amp; connect Facebook</b>, approve access in Meta&apos;s window, and — if you manage more than one Page — choose which Page to publish to.</li></ul><div className="youtube-credential-grid facebook-credential-grid"><label><span>Meta app ID</span><input value={appId} onChange={(event) => setAppId(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "Meta app ID"} autoComplete="off" /></label><label className="full"><span>Meta app secret</span><div><input type={showSecret ? "text" : "password"} value={appSecret} onChange={(event) => setAppSecret(event.target.value)} placeholder={status?.configured ? "Saved — enter only to replace" : "Meta app secret"} autoComplete="off" /><button onClick={() => setShowSecret(!showSecret)}>{showSecret ? "Hide" : "Show"}</button></div></label></div><SetupDone>The connected Page name appears in green.</SetupDone></div></li>
    </ol>
    <div className="youtube-setup-note facebook-note"><CircleHelp size={16} /><p><b>Testing versus production:</b> while the Meta app is in Development mode, only people assigned an app role (admin, developer, or tester) can authorize it. For public multi-user access, request Advanced Access for the listed permissions, complete Business Verification if Meta requires it, and pass App Review.</p></div>
    <SetupTroubleshooting issues={[{ title: "redirect_uri is not allowed", fix: `Open Facebook Login → Settings and add exactly ${redirectUri} under Valid OAuth Redirect URIs. It must be https on localhost — Meta rejects http. Run npm run https:setup if you have not yet, and match the port, path, and trailing slash exactly.` }, { title: "New HTTP Redirect URIs are not allowed", fix: "Meta blocks http:// redirect URIs. Use the https://localhost callback above (run npm run https:setup to enable it) instead of an http://127.0.0.1 address." }, { title: "No Facebook Page found", fix: "Confirm your profile has a role on the Page in Meta Business Settings → Pages, then connect again so the Page appears." }, { title: "Only app administrators can log in", fix: "Development mode only permits app-role users. Add the person as a tester, or complete Advanced Access and App Review for production." }, { title: "Instagram did not connect", fix: "Link the Instagram Professional account to the selected Facebook Page, then reconnect. Instagram also needs a public media URL set in the Instagram connector." }]} />
    <footer><button className="secondary-action" onClick={onCheck} disabled={connecting}><RefreshCw size={15} /> Check connection</button><button className="youtube-connect-button facebook-connect-button" onClick={onConnect} disabled={connecting || status?.connected}>{status?.connected ? <><Check size={16} /> Connected</> : connecting ? <><RefreshCw className="spin" size={16} /> Starting…</> : <><Play size={16} /> {status?.configured && !appId && !appSecret ? "Connect Facebook" : "Save & connect Facebook"}</>}</button></footer>
  </div></div>;
}

export function InstagramSetupGuide({ status, facebookConnected, publicMediaBaseUrl, setPublicMediaBaseUrl, saving, onSave, onCheck, onClose }: { status: InstagramStatus | null; facebookConnected: boolean; publicMediaBaseUrl: string; setPublicMediaBaseUrl: (value: string) => void; saving: boolean; onSave: () => void; onCheck: () => void; onClose: () => void }) {
  return <div className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="instagram-setup-title"><div className="setup-dialog">
    <header><div><PlatformLogo platform={platforms[3]} /><span><strong id="instagram-setup-title">Connect Instagram</strong><small>Professional account • Instagram Reels Publishing API</small></span></div><button onClick={onClose} aria-label="Close Instagram setup"><X size={18} /></button></header>
    {status?.connected && <div className="connection-success"><ShieldCheck size={18} /><span><strong>{status.username} is connected</strong><small>Reelio verified the Instagram account, Meta token, and public media URL.</small></span></div>}
    <div className="id-explainer instagram-id-explainer"><strong>Instagram publishing reuses the Facebook (Meta) login</strong><span>The <b>Connect Facebook</b> button above signs in with Meta and, when your selected Page has a linked Instagram Professional account, saves its <code>instagram_business_account.id</code> and the shared token automatically.</span><span>Only the <b>public media URL</b> below still needs to be entered here, because Meta downloads the finished Reel from a URL.</span></div>
    <ol className="setup-steps">
      <li><span>1</span><div><strong>Switch Instagram to a Professional account and link the Page</strong><ul className="setup-actions"><li>In the Instagram app: Profile → <b>Settings and activity</b> → <b>Account type and tools</b> → <b>Switch to professional account</b> (Creator or Business).</li><li>In Meta Business Settings → <b>Accounts → Instagram accounts</b>, link it to the same Facebook Page you publish with.</li></ul><a href="https://business.facebook.com/settings/instagram-accounts/" target="_blank" rel="noreferrer">Open Instagram accounts in Business Settings <ExternalLink size={13} /></a><SetupDone>The Instagram Professional account is linked to your Facebook Page.</SetupDone></div></li>
      <li><span>2</span><div><strong>Connect through Facebook</strong><ul className="setup-actions"><li>Use <b>Connect Facebook</b> in the Facebook connector above. The Meta login grants <code>instagram_basic</code> and <code>instagram_content_publish</code> and saves your <code>instagram_business_account</code> ID.</li><li>Select the Page whose linked Instagram account you want to publish to.</li></ul>{!facebookConnected && <p className="model-error">Connect Facebook first — Instagram uses that same Meta login.</p>}<SetupDone>The Instagram account ID and shared Meta token are saved.</SetupDone></div></li>
      <li><span>3</span><div><strong>Prepare the public media URL</strong><ul className="setup-actions"><li>Meta&apos;s server downloads the MP4 from a URL; it cannot read this local browser.</li><li>The URL must be public HTTPS, reachable without login, return the actual MP4 bytes, and serve Reelio&apos;s path <code>/jobs/&lt;job-id&gt;/assets/final</code>.</li><li>Do not use localhost, 127.0.0.1, a private LAN address, or a URL requiring cookies.</li></ul><div className="youtube-credential-grid instagram-credential-grid"><label className="full"><span>Public media base URL</span><input value={publicMediaBaseUrl} onChange={(event) => setPublicMediaBaseUrl(event.target.value)} placeholder={status?.publicMediaBaseUrl ?? "https://your-domain.example/media"} autoComplete="url" /></label></div><SetupDone>Opening a completed job&apos;s final asset URL in a private browser plays the MP4 without signing in.</SetupDone></div></li>
    </ol>
    <div className="youtube-setup-note instagram-note"><CircleHelp size={16} /><p><b>The public media route is mandatory:</b> the connection check can verify your account and URL format, but only a real test upload proves Meta can download that specific video. Reelio publishes 9:16 MP4 with H.264 video, AAC audio, and a supported duration/frame rate.</p></div>
    <SetupTroubleshooting issues={[{ title: "instagram_business_account is missing", fix: "The Instagram profile is personal or not linked to the selected Page. Switch it to Professional, link it to the Page, then reconnect Facebook." }, { title: "Meta can verify the account but upload fails", fix: "Open the exact final video URL in a private browser. It must be public HTTPS and return video/mp4 directly without login, HTML, redirect loops, or an expired link." }, { title: "Account is not connected", fix: "Instagram identity comes from the Facebook (Meta) login. Connect Facebook and select the Page linked to this Instagram account." }, { title: "Works only for app administrators", fix: "That is expected in Development mode. Add testers for testing or complete Advanced Access, Business Verification, and App Review." }]} />
    <footer><button className="secondary-action" onClick={onCheck} disabled={saving}><RefreshCw size={15} /> Check connection</button><button className="youtube-connect-button instagram-connect-button" onClick={onSave} disabled={saving || !publicMediaBaseUrl}>{saving ? <><RefreshCw className="spin" size={16} /> Checking…</> : <><ShieldCheck size={16} /> Save & check Instagram</>}</button></footer>
  </div></div>;
}
